version: '3'
services:
  elasticsearch:
    image: elasticsearch:5.6.10
    volumes:
        - es-data:/usr/share/elasticsearch/data
        - ./es/config:/usr/share/elasticsearch/config
    ports:
        - 9200:9200
    expose:
        - 9300
    environment:
      ES_JAVA_OPTS: "-Xms400m -Xmx400m"
    ulimits:
        nofile:
            soft: 65536
            hard: 65536
  kibana:
    image: kibana:5.6.10
    links:
        - elasticsearch:elasticsearch
    ports:
        - 5601:5601

volumes:
    es-data:
        driver: local
